apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lu-broker
  description: This is a module used when building rabbitmq based workers.
  annotations:
    github.com/project-slug: BonnierNews/lu-broker
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: bn-developer-data-infra
  dependsOn:
    - resource:default/lu-server
    - resource:default/lu-logger