version: "3"
services:
  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  rabbitmq:
    build: ./rabbit-dev
    ports:
      - "5672:5672"
      - "15672:15672"
